name: Repository Created Test

# on:
#   repository:
#     types:
#       - created

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  repository-created:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Repository created!"
        run: echo ls
        run: echo pwd

      # Add more steps as needed for your specific use case
